import assert from 'node:assert/strict';import fs from 'node:fs';import {dominates,retainSolution,makeRecord,archiveDomain} from './dist/solution-archive.js';import {score} from './dist/solver.js';
assert.equal(dominates({recipeId:1,power:20,fortitude:20,left:4,right:4,slots:3,colors:[1]},{recipeId:1,power:10,fortitude:10,left:0,right:0,slots:0,colors:[1]}),false,'Longer range cannot delete a shorter-range archive record');
const a={recipeId:1,power:10,fortitude:10,left:4,right:0,slots:3,colors:[1,2]},b={...a};assert.equal(dominates(a,b),false);assert.ok(dominates({...a,power:11},b));assert.ok(!dominates({...a,power:11,fortitude:9},b));assert.ok(!dominates({...a,left:3,right:1},b));assert.ok(!dominates({...a,colors:[1]},b));assert.ok(dominates({...a,colors:[1,2,3]},b));assert.notEqual(archiveDomain(1),archiveDomain(1,true));
const r={id:1,color:1,areas:[{effects:[{type:3,params:[100]},{type:4,params:[100]}]},{effects:[{type:3,params:[100]},{type:4,params:[100]}]}]},solution=(areas,total,n=1)=>({placements:Array.from({length:n},()=>({cells:[]})),score:{activeAreas:areas,total}}),entries=[];assert.ok(retainSolution(r,entries,solution([0],1)));assert.ok(!retainSolution(r,entries,solution([0],2)));assert.ok(retainSolution(r,entries,solution([0],0)));assert.ok(retainSolution(r,entries,solution([1],0)));assert.equal(entries.length,2);assert.ok(retainSolution(r,entries,solution([0,1],0)));assert.equal(entries.length,1);
const mutable=solution([0],0,2),snapshot=[];retainSolution(r,snapshot,mutable);mutable.placements.pop();mutable.score.activeAreas.push(1);assert.equal(snapshot[0].result.placements.length,2);assert.deepEqual(snapshot[0].result.score.activeAreas,[0]);
const data=JSON.parse(fs.readFileSync('dist/data.json')),archive=JSON.parse(fs.readFileSync('dist/solution-archive-data.json'));let count=0;for(const [domain,es]of Object.entries(archive.domains)){const r=data.recipes.find(r=>r.id===Number(domain.split(':')[0]));assert.equal(new Set(es.map(e=>e.areas)).size,es.length);for(const e of es){assert.deepEqual(e.result.score,score(r,data.characters[r.character].skills,e.result.placements));assert.deepEqual(makeRecord(r,e.result),e);assert.ok(!es.some(x=>x!==e&&dominates(x,e)));if(domain.endsWith('no-tier3'))assert.ok(e.result.placements.every(p=>p.tier!==3));count++;}}
console.log('PASS archive semantics, equal-capability area retention, lower penalty replacement, tier separation, verified records:',count);

assert.equal(dominates({...a,recipeId:2,power:999999,fortitude:999999},a),false);assert.throws(()=>retainSolution({...r,id:2},entries,solution([0],0)),/different recipes/);
